apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-ingress
spec:
  ingressClassName: nginx  # Add this line
  rules:
  - host: localhost
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nodejs-production-service
            port:
              number: 8080
      # - pathType: Prefix
      #   path: /nodejsproduction
      #   backend:
      #     service:
      #       name: nodejs-production-service
      #       port:
      #         number: 8080
